language: php

php:
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - export PATH="$PATH:/home/travis/.composer/vendor/bin"

install:
  - composer install

jobs:
  include:
    - script: composer lint
    - script: composer test
